spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-3-7-66-173.ap-south-1.compute.amazonaws.com:6603/microservdb
    username: microserv
    password: testmicroserv
    testOnBorrow: true
    validationQuery: SELECT 1
    max-lifetime: 30000



  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false
    tablePrefix: batch_config.BATCH_

datasource:
  batch:
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://ec2-3-7-66-173.ap-south-1.compute.amazonaws.com:6603/batch_config
      username: batchusr
      password: batchpassword
      testOnBorrow: true
      validationQuery: SELECT 1
      max-lifetime: 30000


  #  datasource:
#    url: jdbc:h2:mem:testdb
#
  h2:
    console:
      enabled: true
      path: /h2-console
